apiVersion: redis.kun/v1alpha1
kind: DistributedRedisCluster
metadata:
  annotations:
    redis.kun/scope: cluster-scoped
  name: example-distributedrediscluster
  labels:
    app: redis-cluster
spec:
  # Add fields here
  masterSize: 3
  clusterReplicas: 5
  image: redis:7.0.14
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: redis-cluster
      matchLabelKeys:
        - statefulSet
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: redis-cluster
      matchLabelKeys:
        - statefulSet