# Copyright 2023 bytetrade
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM rclone/rclone:1.63.1 AS rclone

FROM redis:6.2.13-alpine3.18

RUN apk --no-cache add ca-certificates fuse3 tzdata && \
  echo "user_allow_other" >> /etc/fuse.conf

COPY --from=rclone /usr/local/bin/rclone /usr/local/bin/rclone 

RUN addgroup -g 1009 rclone && adduser -u 1009 -Ds /bin/sh -G rclone rclone
ENV XDG_CONFIG_HOME=/config
WORKDIR /data

COPY tools/scripts/. /usr/local/bin/
RUN chmod +x /usr/local/bin/redis-tools.sh

ENTRYPOINT [ "/usr/local/bin/redis-tools.sh" ]
